# Generated by Django 3.2.3 on 2024-01-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aetsa_transcript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('translated_tumor_peptide', models.CharField(max_length=100, null=True)),
                ('gene_id', models.CharField(max_length=50, null=True)),
                ('gene_symbol', models.CharField(max_length=30, null=True)),
                ('gene_element', models.CharField(max_length=10, null=True)),
                ('cdna_location', models.CharField(max_length=80, null=True)),
                ('cdna_sequence', models.TextField(null=True)),
                ('putative_neoantigen_type', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'aetsa_transcript',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='aetsa_transcript_mutant_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tumor_type', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'aetsa_transcript_mutant_mapping',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='hla_in_patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hla_type', models.CharField(max_length=20, null=True)),
                ('class_type', models.CharField(max_length=5, null=True)),
                ('patient_number', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'hla_in_patient',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='mtsa_dna_transcript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_id', models.CharField(max_length=50, null=True)),
                ('transcript_id', models.CharField(max_length=50)),
                ('gene_symbol', models.CharField(max_length=30, null=True)),
                ('chromosome', models.CharField(max_length=25, null=True)),
                ('start', models.IntegerField(null=True)),
                ('stop', models.IntegerField(null=True)),
                ('reference', models.CharField(max_length=10, null=True)),
                ('variant', models.CharField(max_length=10, null=True)),
                ('mutation', models.CharField(max_length=20, null=True)),
                ('protein_position', models.CharField(max_length=20, null=True)),
                ('variant_type', models.CharField(max_length=20, null=True)),
                ('variant_frequency', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'mtsa_dna_transcript',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='mtsa_dna_transcript_mutant_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tumor_type', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'mtsa_dna_transcript_mutant_mapping',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='mtsa_rna_transcript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_id', models.CharField(max_length=50, null=True)),
                ('transcript_id', models.CharField(max_length=50)),
                ('gene_symbol', models.CharField(max_length=30, null=True)),
                ('variant_position', models.CharField(max_length=30, null=True)),
                ('allele_ref', models.CharField(max_length=10, null=True)),
                ('allele_tumor', models.CharField(max_length=10, null=True)),
                ('amino_acids_change', models.CharField(max_length=10, null=True)),
                ('protein_position', models.IntegerField(null=True)),
                ('wildtype_protein', models.TextField(null=True)),
                ('variant_frequency', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'mtsa_rna_transcript',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='mtsa_rna_transcript_mutant_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tumor_type', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'mtsa_rna_transcript_mutant_mapping',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='mutant_peptide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tumor_protein', models.CharField(max_length=30, null=True)),
                ('normal_protein', models.CharField(max_length=30, null=True)),
                ('hla_type', models.CharField(max_length=20, null=True)),
                ('length', models.IntegerField(null=True)),
                ('amino_acids_change', models.CharField(max_length=10, null=True)),
                ('pos', models.IntegerField(null=True)),
                ('ic50_mut', models.FloatField(null=True)),
                ('ic50_wild', models.FloatField(null=True)),
                ('percent_mut', models.FloatField(null=True)),
                ('percent_wild', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'mutant_peptide',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='patient_aetsa_score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tumor_read_count', models.IntegerField(null=True)),
                ('normal_read_count', models.IntegerField(null=True)),
                ('sum_of_tumor_and_normal_read_count', models.IntegerField(null=True)),
                ('total_tumor_read_count', models.IntegerField(null=True)),
                ('total_normal_read_count', models.IntegerField(null=True)),
                ('sum_of_total_tumor_and_normal_read_count', models.IntegerField(null=True)),
                ('tumor_average_read_depth', models.FloatField(null=True)),
                ('normal_average_read_depth', models.FloatField(null=True)),
                ('sum_of_expected_read_count', models.IntegerField(null=True)),
                ('average_depth_ratio', models.FloatField(null=True)),
                ('element_read_proportion', models.FloatField(null=True)),
                ('sum_of_element_read_count', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'patient_aetsa_score',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='patient_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_from', models.CharField(max_length=20, null=True)),
                ('tumor_type', models.CharField(max_length=20, null=True)),
                ('patient_number', models.CharField(max_length=30, null=True)),
                ('source', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'patient_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='patient_transcript_score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tpm_normal', models.FloatField(null=True)),
                ('tpm_tumor', models.FloatField(null=True)),
                ('fold_change', models.FloatField(null=True)),
                ('tumor_dna_depth', models.IntegerField(null=True)),
                ('tumor_dna_vaf', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'patient_transcript_score',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='peptide_selection_score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tumor_protein', models.CharField(max_length=30, null=True)),
                ('hla_type', models.CharField(max_length=20, null=True)),
                ('best_cleavage_position', models.IntegerField(null=True)),
                ('best_cleavage_score', models.FloatField(null=True)),
                ('predicted_stability', models.FloatField(null=True)),
                ('half_life', models.FloatField(null=True)),
                ('stability_rank', models.FloatField(null=True)),
                ('hydro_avg_score', models.FloatField(null=True)),
                ('foreignness_score', models.FloatField(null=True)),
                ('IEDB_anno', models.CharField(max_length=255, null=True)),
                ('dissimilarity', models.FloatField(null=True)),
                ('cterm_7mer_gravy_score', models.FloatField(null=True)),
                ('max_7mer_gravy_score', models.FloatField(null=True)),
                ('length', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'peptide_selection_score',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('ip', models.CharField(max_length=25, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('enroll_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='user_job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.CharField(default='WAITING', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user_info')),
            ],
            options={
                'db_table': 'user_job',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='peptide_selection_score',
            index=models.Index(fields=['tumor_protein', 'hla_type'], name='peptide_sel_tumor_p_7bbd3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='peptide_selection_score',
            unique_together={('tumor_protein', 'hla_type')},
        ),
        migrations.AddField(
            model_name='patient_transcript_score',
            name='dna_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_transcript_score_d', to='app.mtsa_dna_transcript'),
        ),
        migrations.AddField(
            model_name='patient_transcript_score',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient_info'),
        ),
        migrations.AddField(
            model_name='patient_transcript_score',
            name='rna_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_transcript_score_r', to='app.mtsa_rna_transcript'),
        ),
        migrations.AlterUniqueTogether(
            name='patient_info',
            unique_together={('sample_from', 'patient_number')},
        ),
        migrations.AddField(
            model_name='patient_aetsa_score',
            name='aetsa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aetsa_transcript'),
        ),
        migrations.AddField(
            model_name='patient_aetsa_score',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient_info'),
        ),
        migrations.AddField(
            model_name='mutant_peptide',
            name='peptide_selection_score_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutant_peptide', to='app.peptide_selection_score'),
        ),
        migrations.AddField(
            model_name='mtsa_rna_transcript_mutant_mapping',
            name='mtsa_rna_transcript_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mtsa_rna_transcript'),
        ),
        migrations.AddField(
            model_name='mtsa_rna_transcript_mutant_mapping',
            name='mutant_peptide_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mutant_peptide'),
        ),
        migrations.AlterUniqueTogether(
            name='mtsa_rna_transcript',
            unique_together={('variant_position', 'allele_ref', 'allele_tumor')},
        ),
        migrations.AddField(
            model_name='mtsa_dna_transcript_mutant_mapping',
            name='mtsa_dna_transcript_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mtsa_dna_transcript'),
        ),
        migrations.AddField(
            model_name='mtsa_dna_transcript_mutant_mapping',
            name='mutant_peptide_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mutant_peptide'),
        ),
        migrations.AddIndex(
            model_name='mtsa_dna_transcript',
            index=models.Index(fields=['gene_symbol'], name='mtsa_dna_tr_gene_sy_173dec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mtsa_dna_transcript',
            unique_together={('chromosome', 'start', 'stop', 'reference', 'variant')},
        ),
        migrations.AddField(
            model_name='aetsa_transcript_mutant_mapping',
            name='aetsa_transcript_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aetsa_transcript'),
        ),
        migrations.AddField(
            model_name='aetsa_transcript_mutant_mapping',
            name='mutant_peptide_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mutant_peptide'),
        ),
        migrations.AddIndex(
            model_name='aetsa_transcript',
            index=models.Index(fields=['gene_symbol'], name='aetsa_trans_gene_sy_17d6c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aetsa_transcript',
            unique_together={('translated_tumor_peptide', 'cdna_location', 'gene_element')},
        ),
        migrations.AlterUniqueTogether(
            name='patient_transcript_score',
            unique_together={('rna_id', 'dna_id', 'patient_id')},
        ),
        migrations.AlterUniqueTogether(
            name='patient_aetsa_score',
            unique_together={('patient_id', 'aetsa_id', 'tumor_read_count', 'normal_read_count', 'sum_of_tumor_and_normal_read_count', 'total_tumor_read_count', 'total_normal_read_count', 'sum_of_total_tumor_and_normal_read_count', 'tumor_average_read_depth', 'normal_average_read_depth', 'sum_of_expected_read_count', 'average_depth_ratio', 'element_read_proportion', 'sum_of_element_read_count')},
        ),
        migrations.AddIndex(
            model_name='mutant_peptide',
            index=models.Index(fields=['tumor_protein', 'hla_type'], name='mutant_pept_tumor_p_18f892_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mutant_peptide',
            unique_together={('tumor_protein', 'normal_protein', 'hla_type')},
        ),
        migrations.AlterUniqueTogether(
            name='mtsa_rna_transcript_mutant_mapping',
            unique_together={('mtsa_rna_transcript_id', 'mutant_peptide_id', 'tumor_type')},
        ),
        migrations.AlterUniqueTogether(
            name='mtsa_dna_transcript_mutant_mapping',
            unique_together={('mtsa_dna_transcript_id', 'mutant_peptide_id', 'tumor_type')},
        ),
        migrations.AlterUniqueTogether(
            name='aetsa_transcript_mutant_mapping',
            unique_together={('aetsa_transcript_id', 'mutant_peptide_id', 'tumor_type')},
        ),
    ]
