# Generated by Django 3.2.3 on 2024-02-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_aetsa_transcript_gene_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetsa_transcript',
            name='gene_element',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
