# Generated by Django 3.2.3 on 2024-02-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_aetsa_transcript_gene_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='hla_in_patient',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient_info'),
        ),
        migrations.AlterUniqueTogether(
            name='hla_in_patient',
            unique_together={('hla_type', 'patient_id')},
        ),
        migrations.RemoveField(
            model_name='hla_in_patient',
            name='patient_number',
        ),
    ]
