# Generated by Django 3.2.3 on 2024-02-10 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240202_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='validated_peptide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tumor_protein', models.CharField(max_length=30, null=True)),
                ('hla_type', models.CharField(max_length=20, null=True)),
                ('pmhc', models.IntegerField(null=True)),
                ('tcr', models.IntegerField(null=True)),
                ('deepneo', models.IntegerField(null=True)),
                ('iedb_tcr', models.IntegerField(null=True)),
                ('prime', models.IntegerField(null=True)),
                ('best_cleavage_position', models.IntegerField(null=True)),
                ('best_cleavage_score', models.FloatField(null=True)),
                ('predicted_stability', models.FloatField(null=True)),
                ('half_life', models.FloatField(null=True)),
                ('stability_rank', models.FloatField(null=True)),
                ('hydro_avg_score', models.FloatField(null=True)),
                ('foreignness_score', models.FloatField(null=True)),
                ('IEDB_anno', models.CharField(max_length=255, null=True)),
                ('dissimilarity', models.FloatField(null=True)),
                ('cterm_7mer_gravy_score', models.FloatField(null=True)),
                ('max_7mer_gravy_score', models.FloatField(null=True)),
                ('length', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'validated_peptide',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='validated_peptide',
            index=models.Index(fields=['tumor_protein', 'hla_type'], name='validated_p_tumor_p_4042cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='validated_peptide',
            unique_together={('tumor_protein', 'hla_type')},
        ),
        migrations.AddField(
            model_name='peptide_selection_score',
            name='validated_peptide_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.validated_peptide'),
        ),
    ]
