# Generated by Django 3.2.3 on 2024-02-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240210_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='validated_peptide',
            name='iedb_mhc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='validated_peptide',
            name='ieltas',
            field=models.IntegerField(null=True),
        ),
    ]
