# Generated by Django 3.2.3 on 2024-02-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240211_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutant_peptide',
            name='pos',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
