# Generated by Django 3.2.3 on 2024-02-20 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_mutant_peptide_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='shared_pep_in_patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aetsa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aetsa_transcript')),
                ('dna_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mtsa_dna_transcript')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient_info')),
                ('rna_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mtsa_rna_transcript')),
            ],
            options={
                'db_table': 'shared_pep_in_patient',
                'managed': True,
                'unique_together': {('patient_id', 'rna_id', 'dna_id', 'aetsa_id')},
            },
        ),
    ]
