# Generated by Django 3.2.3 on 2024-02-20 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_shared_pep_in_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_pep_in_patient',
            name='mutant_peptide_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mutant_peptide'),
        ),
        migrations.AlterUniqueTogether(
            name='shared_pep_in_patient',
            unique_together={('patient_id', 'rna_id', 'dna_id', 'aetsa_id', 'mutant_peptide_id')},
        ),
    ]
