# Generated by Django 3.2.3 on 2024-02-22 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240220_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='shared_pep_mtsa_rna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mutant_peptide_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mutant_peptide')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient_info')),
                ('rna_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mtsa_rna_transcript')),
            ],
            options={
                'db_table': 'shared_pep_mtsa_rna',
                'managed': True,
                'unique_together': {('patient_id', 'rna_id', 'mutant_peptide_id')},
            },
        ),
        migrations.CreateModel(
            name='shared_pep_mtsa_dna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dna_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mtsa_dna_transcript')),
                ('mutant_peptide_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mutant_peptide')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient_info')),
            ],
            options={
                'db_table': 'shared_pep_mtsa_dna',
                'managed': True,
                'unique_together': {('patient_id', 'dna_id', 'mutant_peptide_id')},
            },
        ),
        migrations.CreateModel(
            name='shared_pep_aetsa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aetsa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aetsa_transcript')),
                ('mutant_peptide_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mutant_peptide')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient_info')),
            ],
            options={
                'db_table': 'shared_pep_aetsa',
                'managed': True,
                'unique_together': {('patient_id', 'aetsa_id', 'mutant_peptide_id')},
            },
        ),
    ]
