# Generated by Django 3.2.3 on 2024-02-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_shared_pep_aetsa_shared_pep_mtsa_dna_shared_pep_mtsa_rna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtsa_rna_transcript',
            name='variant_position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
