# Generated by Django 3.2.3 on 2024-02-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_mtsa_rna_transcript_variant_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_pep_aetsa',
            name='tumor_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shared_pep_mtsa_dna',
            name='tumor_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shared_pep_mtsa_rna',
            name='tumor_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
