# Generated by Django 3.2.3 on 2024-02-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20240226_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='hla_in_patient',
            name='tumor_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
