# Generated by Django 3.2.3 on 2024-03-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_hla_in_patient_tumor_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mutant_peptide',
            index=models.Index(fields=['tumor_protein'], name='mutant_pept_tumor_p_35280f_idx'),
        ),
        migrations.AddIndex(
            model_name='mutant_peptide',
            index=models.Index(fields=['hla_type'], name='mutant_pept_hla_typ_aca12c_idx'),
        ),
    ]
