# Generated by Django 3.2.3 on 2024-05-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20240318_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtsa_dna_transcript',
            name='variant',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
