# Generated by Django 3.2.3 on 2024-05-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_mtsa_dna_transcript_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtsa_dna_transcript',
            name='reference',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
