# Generated by Django 3.2.3 on 2024-05-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_mtsa_dna_transcript_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtsa_dna_transcript',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mtsa_dna_transcript',
            name='variant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
