# Generated by Django 3.2.3 on 2024-05-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20240514_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtsa_dna_transcript',
            name='reference',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='mtsa_dna_transcript',
            name='variant',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
