# Generated by Django 3.2.3 on 2024-06-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20240514_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='activate_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='email_uuid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='is_activate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_job',
            name='uuid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
