# Generated by Django 3.2.3 on 2024-06-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20240619_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='email_uuid',
            new_name='mail_uuid',
        ),
    ]
