# Generated by Django 3.2.3 on 2024-07-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_email_uuid_user_info_mail_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_job',
            name='pep_count',
            field=models.IntegerField(null=True),
        ),
    ]
