# Generated by Django 3.2.3 on 2024-01-28 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20240123_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='aetsa_transcript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('translated_tumor_peptide', models.CharField(max_length=100, null=True)),
                ('gene_id', models.CharField(max_length=50, null=True)),
                ('gene_symbol', models.CharField(max_length=30, null=True)),
                ('gene_element', models.CharField(max_length=10, null=True)),
                ('cdna_location', models.CharField(max_length=80, null=True)),
                ('cdna_sequence', models.TextField(null=True)),
                ('putative_neoantigen_type', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'aetsa_transcript',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='mtsa_dna_transcript',
            name='gene_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mtsa_dna_transcript',
            unique_together={('chromosome', 'start', 'stop', 'reference', 'variant', 'tumor_type')},
        ),
        migrations.CreateModel(
            name='patient_aetsa_score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tumor_read_count', models.IntegerField(null=True)),
                ('normal_read_count', models.IntegerField(null=True)),
                ('sum_of_tumor_and_normal_read_count', models.IntegerField(null=True)),
                ('total_tumor_read_count', models.IntegerField(null=True)),
                ('total_normal_read_count', models.IntegerField(null=True)),
                ('sum_of_total_tumor_and_normal_read_count', models.IntegerField(null=True)),
                ('tumor_average_read_depth', models.FloatField(null=True)),
                ('normal_average_read_depth', models.FloatField(null=True)),
                ('sum_of_expected_read_count', models.IntegerField(null=True)),
                ('average_depth_ratio', models.FloatField(null=True)),
                ('element_read_proportion', models.FloatField(null=True)),
                ('sum_of_element_read_count', models.IntegerField(null=True)),
                ('aetsa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aetsa_transcript')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient_info')),
            ],
            options={
                'db_table': 'patient_aetsa_score',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='aetsa_transcript_mutant_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tumor_type', models.CharField(max_length=20, null=True)),
                ('aetsa_transcript_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aetsa_transcript')),
                ('mutant_peptide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mutant_peptide')),
            ],
            options={
                'db_table': 'aetsa_transcript_mutant_mapping',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='aetsa_transcript',
            index=models.Index(fields=['gene_symbol'], name='aetsa_trans_gene_sy_17d6c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aetsa_transcript',
            unique_together={('translated_tumor_peptide', 'cdna_location', 'gene_element')},
        ),
        migrations.AlterUniqueTogether(
            name='patient_aetsa_score',
            unique_together={('tumor_read_count', 'normal_read_count', 'sum_of_tumor_and_normal_read_count', 'total_tumor_read_count', 'total_normal_read_count', 'sum_of_total_tumor_and_normal_read_count', 'tumor_average_read_depth', 'normal_average_read_depth', 'sum_of_expected_read_count', 'average_depth_ratio', 'element_read_proportion', 'sum_of_element_read_count')},
        ),
        migrations.AlterUniqueTogether(
            name='aetsa_transcript_mutant_mapping',
            unique_together={('aetsa_transcript_id', 'mutant_peptide_id', 'tumor_type')},
        ),
    ]
