# Generated by Django 3.2.3 on 2024-01-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20240123_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='aetsa_transcript_t',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('translated_tumor_peptide', models.CharField(max_length=100, null=True)),
                ('gene_id', models.CharField(max_length=50, null=True)),
                ('gene_symbol', models.CharField(max_length=30, null=True)),
                ('gene_element', models.CharField(max_length=10, null=True)),
                ('cdna_location', models.CharField(max_length=80, null=True)),
                ('cdna_sequence', models.TextField(null=True)),
                ('putative_neoantigen_type', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'aetsa_transcript_t',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='aetsa_transcript',
            unique_together=None,
        ),
        migrations.AddIndex(
            model_name='aetsa_transcript_t',
            index=models.Index(fields=['gene_symbol'], name='aetsa_trans_gene_sy_97e76d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aetsa_transcript_t',
            unique_together={('translated_tumor_peptide', 'cdna_location', 'gene_element')},
        ),
        migrations.AlterField(
            model_name='aetsa_transcript_mutant_mapping',
            name='aetsa_transcript_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aetsa_transcript_t'),
        ),
        migrations.AlterField(
            model_name='patient_aetsa_score',
            name='aetsa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aetsa_transcript_t'),
        ),
        migrations.DeleteModel(
            name='aetsa_transcript',
        ),
    ]
